language: php
matrix:
  - dist: precise
    env:  MAGENTO_VERSION=magento-mirror-1.7.0.2
    php:  5.3.29
  - dist: precise
    env:  MAGENTO_VERSION=magento-mirror-1.8.1.0
    php:  5.3.29
  - dist: precise
    env:  MAGENTO_VERSION=magento-mirror-1.9.3.7
    php:  5.3.29
script:
  - curl -sSL https://raw.githubusercontent.com/LukeLeber/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - lukeleber@gmail.com
    on_success: always
    on_failure: always
