language: php
#php:
#  - 5.4
#  - 5.5
#env:
#  global:
#    - MAGENTO_DB_ALLOWSAME=1
#    - SKIP_CLEANUP=1
#   - MAGENTO_VERSION=magento-mirror-1.7.0.2
#  - MAGENTO_VERSION=magento-mirror-1.9.3.4
#  - MAGENTO_VERSION=magento-mirror-1.8.1.0
matrix:
  include:
    - dist: precise
      env:  MAGENTO_VERSION=magento-mirror-1.6.2.0
      php: 5.2.10
#    - dist: precise
#      env:  MAGENTO_VERSION=magento-mirror-1.7.0.2
#      php: 5.3.29
  exclude:

script:
  - curl -sSL https://raw.githubusercontent.com/LukeLeber/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - lukeleber@gmail.com
    on_success: always
    on_failure: always
