language: php
php:
  - 5.5
env:
#  global:
#    - MAGENTO_DB_ALLOWSAME=1
#    - SKIP_CLEANUP=1
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
script:
  - curl -sSL https://github.com/LukeLeber/MageTestStand/blob/master/setup.sh | dos2unix | bash
notifications:
  email:
    recipients:
      - lukeleber@gmail.com
    on_success: always
    on_failure: always
