language: php

before_install:
  - sudo apt-get purge mysql-* -y
  - sudo rm -rf /etc/mysql /var/lib/mysql
  - sudo apt-get autoremove -y
  - sudo apt-get autoclean -y
  - sudo wget https://repo.percona.com/apt/percona-release_0.1-4.$(lsb_release -sc)_all.deb
  - sudo dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb
  - sudo apt-get update -y
  - sudo apt-get install percona-server-server-5.5 -y

php:
  - 5.3
#  - 5.4
#  - 5.5

env:
  global:
    - MAGENTO_VERSION=magento-mirror-1.7.0.2
#    - MAGENTO_VERSION=magento-mirror-1.8.1.0
#    - MAGENTO_VERSION=magento-mirror-1.9.2.2

matrix:
  include:
    - php: 5.3
      dist: precise    
script:
  - curl -sSL https://raw.githubusercontent.com/LukeLeber/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - lukeleber@gmail.com
    on_success: always
    on_failure: always
