language: php
#php:
#  - 5.4
#  - 5.5
#env:
#  global:
#    - MAGENTO_DB_ALLOWSAME=1
#    - SKIP_CLEANUP=1
#   - MAGENTO_VERSION=magento-mirror-1.7.0.2
#  - MAGENTO_VERSION=magento-mirror-1.9.3.4
#  - MAGENTO_VERSION=magento-mirror-1.8.1.0
before_install:
  - sudo apt-get purge mysql-*
  - sudo rm -rf /etc/mysql /var/lib/mysql
  - sudo apt-get autoremove
  - sudo apt-get autoclean
  - wget https://repo.percona.com/apt/percona-release_0.1-4.$(lsb_release -sc)_all.deb
  - dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb
  - apt-get update
  - apt-get install percona-server-server-5.5

matrix:
  include:
#    - dist: precise
#      env:  MAGENTO_VERSION=magento-mirror-1.7.0.2
#      php: 5.3.29
    - dist:  trusty
      env:   MAGENTO_VERSION=magento-mirror-1.7.0.2
      php:   5.4.45
      mysql: 5.5
  exclude:

script:
  - curl -sSL https://raw.githubusercontent.com/LukeLeber/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - lukeleber@gmail.com
    on_success: always
    on_failure: always
