language: php
php:
  - 5.5
  - 5.6
env:
#  global:
#    - MAGENTO_DB_ALLOWSAME=1
#    - SKIP_CLEANUP=1
  - MAGENTO_VERSION=magento-mirror-1.9.3.4
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
script:
  - curl -sSL https://raw.githubusercontent.com/LukeLeber/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - lukeleber@gmail.com
    on_success: always
    on_failure: always
